server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medical?serverTimezone=UTC
    username: root
    password: zeng282512@
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    # 与项目代码分离的静态资源路径，即：文件上传保存根路径
    upload-path: E:/Code/files/medicalFiles
    resources:
      # 除了带上Spring Boot默认的静态资源路径之外，加上file:${web.upload-path}指向外部的文件资源上传路径。该路径下的静态资源可以直接对外提供HTTP访问服务。
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${spring.web.upload-path}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-result-set-type:
  global-config:
    banner: false
    db-config:
      # id自动生成配置
      id-type: assign_id
      #数据库前缀配置
      table-prefix: tb_
      # 逻辑删除字段配置
      logic-delete-field: deleted
      logic-not-delete-value: 1
      logic-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity



